import type {Metadata} from 'next';
import {Lato} from 'next/font/google';
import './globals.css';
import {Toaster} from '@/components/ui/sonner';
import {SessionProvider} from 'next-auth/react';
import {auth} from '@/auth';
import QueryProvider from '@/components/QueryProvider';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: ['italic', 'normal'],
});

export const metadata: Metadata = {
  title: 'Mo Skin Care',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html
      lang='en'
      className='h-full bg-white'
    >
      <body className={lato.className} suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          <QueryProvider>
            <div>
              {children}
            </div>
            <Toaster />
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
