import type {Metadata} from 'next';
import {Lato} from 'next/font/google';
import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: ['italic', 'normal'],
});

export const metadata: Metadata = {
  title: 'Mo Skin Care',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full bg-secondary'
    >
      <body className={lato.className}>
        <div className=''>
          <main className=''>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
